export const authConstant = {
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_NAME_CHANGE: 'USER_NAME_CHANGE',
}

export const userConstants = {
  GET_REALTIME_USERS: 'GET_REALTIME_USERS',
  GET_REALTIME_MESSAGES: 'GET_REALTIME_MESSAGES',
}
